# Generated by Django 4.2.2 on 2023-06-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cod_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao', models.CharField(blank=True, max_length=120, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('ie', models.CharField(blank=True, max_length=13, null=True)),
                ('im', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('matriz', models.BooleanField(blank=True, null=True)),
                ('crt', models.CharField(blank=True, max_length=1, null=True)),
                ('cnae', models.CharField(blank=True, max_length=7, null=True)),
                ('iest', models.CharField(blank=True, max_length=18, null=True)),
                ('suframa', models.CharField(blank=True, max_length=10, null=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('cod_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('endereco', models.CharField(blank=True, max_length=70, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('ie', models.CharField(blank=True, max_length=18, null=True)),
                ('im', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'enderecos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrpEmpresa',
            fields=[
                ('grp_empresa', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grp_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('cod_municipio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('municipio', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('cod_ibge', models.CharField(blank=True, max_length=2, null=True)),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'uf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('cod_empresa', models.OneToOneField(db_column='cod_empresa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='Id_Empresa', serialize=False, to='Site.empresa')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('celular', models.CharField(blank=True, max_length=13, null=True)),
                ('cod_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Id_Usuario', to='Site.empresa')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
                'unique_together': {('cod_empresa', 'cod_usuario')},
            },
        ),
    ]
