# Generated by Django 4.2.2 on 2023-07-03 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cod_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Id_Usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
