# Generated by Django 4.2.2 on 2023-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_alter_usuario_cod_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
