# Generated by Django 4.2.2 on 2023-07-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
