# Generated by Django 4.2.2 on 2023-07-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
    ]
