# Generated by Django 4.2.2 on 2023-07-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': False},
        ),
    ]
